name: Generate Assets

on:
  schedule:
    # Run once every 24 hours (at 00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-light.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Generate light stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&theme=default
          path: dist/github-stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate dark stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&theme=github_dark
          path: dist/github-stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate light langs card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=320&langs_count=5&theme=default
          path: dist/github-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate dark langs card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=320&langs_count=5&theme=github_dark
          path: dist/github-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push assets to the output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
